# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import privacy_pb2 as privacy__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in privacy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrivacyServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Mask = channel.unary_unary(
                '/privacy.local.PrivacyService/Mask',
                request_serializer=privacy__pb2.MaskRequest.SerializeToString,
                response_deserializer=privacy__pb2.MaskResponse.FromString,
                _registered_method=True)
        self.MaskRecord = channel.unary_unary(
                '/privacy.local.PrivacyService/MaskRecord',
                request_serializer=privacy__pb2.MaskRecordRequest.SerializeToString,
                response_deserializer=privacy__pb2.MaskRecordResponse.FromString,
                _registered_method=True)
        self.Hash = channel.unary_unary(
                '/privacy.local.PrivacyService/Hash',
                request_serializer=privacy__pb2.HashRequest.SerializeToString,
                response_deserializer=privacy__pb2.HashResponse.FromString,
                _registered_method=True)
        self.DPCount = channel.unary_unary(
                '/privacy.local.PrivacyService/DPCount',
                request_serializer=privacy__pb2.DPRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPSum = channel.unary_unary(
                '/privacy.local.PrivacyService/DPSum',
                request_serializer=privacy__pb2.DPRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPMean = channel.unary_unary(
                '/privacy.local.PrivacyService/DPMean',
                request_serializer=privacy__pb2.DPRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.KAnonymizeRecord = channel.unary_unary(
                '/privacy.local.PrivacyService/KAnonymizeRecord',
                request_serializer=privacy__pb2.KAnonymizeRequest.SerializeToString,
                response_deserializer=privacy__pb2.KAnonymizeResponse.FromString,
                _registered_method=True)
        self.KAnonymizeTable = channel.unary_unary(
                '/privacy.local.PrivacyService/KAnonymizeTable',
                request_serializer=privacy__pb2.KAnonymizeTableRequest.SerializeToString,
                response_deserializer=privacy__pb2.KAnonymizeTableResponse.FromString,
                _registered_method=True)
        self.ObfuscateQuery = channel.unary_unary(
                '/privacy.local.PrivacyService/ObfuscateQuery',
                request_serializer=privacy__pb2.ObfuscateQueryRequest.SerializeToString,
                response_deserializer=privacy__pb2.ObfuscateQueryResponse.FromString,
                _registered_method=True)
        self.ClassifyField = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyField',
                request_serializer=privacy__pb2.ClassifyFieldRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyFieldResponse.FromString,
                _registered_method=True)
        self.ClassifyRecord = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyRecord',
                request_serializer=privacy__pb2.ClassifyRecordRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyRecordResponse.FromString,
                _registered_method=True)
        self.ClassifyTable = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyTable',
                request_serializer=privacy__pb2.ClassifyTableRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyTableResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/privacy.local.PrivacyService/Health',
                request_serializer=privacy__pb2.HealthRequest.SerializeToString,
                response_deserializer=privacy__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RecommendParams = channel.unary_unary(
                '/privacy.local.PrivacyService/RecommendParams',
                request_serializer=privacy__pb2.RecommendRequest.SerializeToString,
                response_deserializer=privacy__pb2.RecommendResponse.FromString,
                _registered_method=True)


class PrivacyServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Mask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaskRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPMean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KAnonymizeRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KAnonymizeTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObfuscateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivacyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Mask': grpc.unary_unary_rpc_method_handler(
                    servicer.Mask,
                    request_deserializer=privacy__pb2.MaskRequest.FromString,
                    response_serializer=privacy__pb2.MaskResponse.SerializeToString,
            ),
            'MaskRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.MaskRecord,
                    request_deserializer=privacy__pb2.MaskRecordRequest.FromString,
                    response_serializer=privacy__pb2.MaskRecordResponse.SerializeToString,
            ),
            'Hash': grpc.unary_unary_rpc_method_handler(
                    servicer.Hash,
                    request_deserializer=privacy__pb2.HashRequest.FromString,
                    response_serializer=privacy__pb2.HashResponse.SerializeToString,
            ),
            'DPCount': grpc.unary_unary_rpc_method_handler(
                    servicer.DPCount,
                    request_deserializer=privacy__pb2.DPRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPSum': grpc.unary_unary_rpc_method_handler(
                    servicer.DPSum,
                    request_deserializer=privacy__pb2.DPRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPMean': grpc.unary_unary_rpc_method_handler(
                    servicer.DPMean,
                    request_deserializer=privacy__pb2.DPRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'KAnonymizeRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.KAnonymizeRecord,
                    request_deserializer=privacy__pb2.KAnonymizeRequest.FromString,
                    response_serializer=privacy__pb2.KAnonymizeResponse.SerializeToString,
            ),
            'KAnonymizeTable': grpc.unary_unary_rpc_method_handler(
                    servicer.KAnonymizeTable,
                    request_deserializer=privacy__pb2.KAnonymizeTableRequest.FromString,
                    response_serializer=privacy__pb2.KAnonymizeTableResponse.SerializeToString,
            ),
            'ObfuscateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ObfuscateQuery,
                    request_deserializer=privacy__pb2.ObfuscateQueryRequest.FromString,
                    response_serializer=privacy__pb2.ObfuscateQueryResponse.SerializeToString,
            ),
            'ClassifyField': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyField,
                    request_deserializer=privacy__pb2.ClassifyFieldRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyFieldResponse.SerializeToString,
            ),
            'ClassifyRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyRecord,
                    request_deserializer=privacy__pb2.ClassifyRecordRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyRecordResponse.SerializeToString,
            ),
            'ClassifyTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyTable,
                    request_deserializer=privacy__pb2.ClassifyTableRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyTableResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=privacy__pb2.HealthRequest.FromString,
                    response_serializer=privacy__pb2.HealthResponse.SerializeToString,
            ),
            'RecommendParams': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendParams,
                    request_deserializer=privacy__pb2.RecommendRequest.FromString,
                    response_serializer=privacy__pb2.RecommendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privacy.local.PrivacyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privacy.local.PrivacyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrivacyService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Mask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/Mask',
            privacy__pb2.MaskRequest.SerializeToString,
            privacy__pb2.MaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaskRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/MaskRecord',
            privacy__pb2.MaskRecordRequest.SerializeToString,
            privacy__pb2.MaskRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/Hash',
            privacy__pb2.HashRequest.SerializeToString,
            privacy__pb2.HashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPCount',
            privacy__pb2.DPRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPSum',
            privacy__pb2.DPRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPMean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPMean',
            privacy__pb2.DPRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KAnonymizeRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/KAnonymizeRecord',
            privacy__pb2.KAnonymizeRequest.SerializeToString,
            privacy__pb2.KAnonymizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KAnonymizeTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/KAnonymizeTable',
            privacy__pb2.KAnonymizeTableRequest.SerializeToString,
            privacy__pb2.KAnonymizeTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObfuscateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ObfuscateQuery',
            privacy__pb2.ObfuscateQueryRequest.SerializeToString,
            privacy__pb2.ObfuscateQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyField',
            privacy__pb2.ClassifyFieldRequest.SerializeToString,
            privacy__pb2.ClassifyFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyRecord',
            privacy__pb2.ClassifyRecordRequest.SerializeToString,
            privacy__pb2.ClassifyRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyTable',
            privacy__pb2.ClassifyTableRequest.SerializeToString,
            privacy__pb2.ClassifyTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/Health',
            privacy__pb2.HealthRequest.SerializeToString,
            privacy__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/RecommendParams',
            privacy__pb2.RecommendRequest.SerializeToString,
            privacy__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
