# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import privacy_pb2 as privacy__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in privacy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrivacyServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Mask = channel.unary_unary(
                '/privacy.local.PrivacyService/Mask',
                request_serializer=privacy__pb2.MaskRequest.SerializeToString,
                response_deserializer=privacy__pb2.MaskResponse.FromString,
                _registered_method=True)
        self.MaskRecord = channel.unary_unary(
                '/privacy.local.PrivacyService/MaskRecord',
                request_serializer=privacy__pb2.MaskRecordRequest.SerializeToString,
                response_deserializer=privacy__pb2.MaskRecordResponse.FromString,
                _registered_method=True)
        self.MaskBatch = channel.unary_unary(
                '/privacy.local.PrivacyService/MaskBatch',
                request_serializer=privacy__pb2.MaskBatchRequest.SerializeToString,
                response_deserializer=privacy__pb2.MaskBatchResponse.FromString,
                _registered_method=True)
        self.MaskDataFrame = channel.unary_unary(
                '/privacy.local.PrivacyService/MaskDataFrame',
                request_serializer=privacy__pb2.MaskDataFrameRequest.SerializeToString,
                response_deserializer=privacy__pb2.MaskDataFrameResponse.FromString,
                _registered_method=True)
        self.Hash = channel.unary_unary(
                '/privacy.local.PrivacyService/Hash',
                request_serializer=privacy__pb2.HashRequest.SerializeToString,
                response_deserializer=privacy__pb2.HashResponse.FromString,
                _registered_method=True)
        self.DPCount = channel.unary_unary(
                '/privacy.local.PrivacyService/DPCount',
                request_serializer=privacy__pb2.DPRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPSum = channel.unary_unary(
                '/privacy.local.PrivacyService/DPSum',
                request_serializer=privacy__pb2.DPRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPMean = channel.unary_unary(
                '/privacy.local.PrivacyService/DPMean',
                request_serializer=privacy__pb2.DPRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPHistogram = channel.unary_unary(
                '/privacy.local.PrivacyService/DPHistogram',
                request_serializer=privacy__pb2.DPHistogramRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPHistogramResponse.FromString,
                _registered_method=True)
        self.DPNoisyCount = channel.unary_unary(
                '/privacy.local.PrivacyService/DPNoisyCount',
                request_serializer=privacy__pb2.DPNoisyCountRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPNoisySum = channel.unary_unary(
                '/privacy.local.PrivacyService/DPNoisySum',
                request_serializer=privacy__pb2.DPNoisySumRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPNoisyMean = channel.unary_unary(
                '/privacy.local.PrivacyService/DPNoisyMean',
                request_serializer=privacy__pb2.DPNoisyMeanRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPNoisyHistogram = channel.unary_unary(
                '/privacy.local.PrivacyService/DPNoisyHistogram',
                request_serializer=privacy__pb2.DPNoisyHistogramRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPHistogramResponse.FromString,
                _registered_method=True)
        self.DPChunkedCount = channel.unary_unary(
                '/privacy.local.PrivacyService/DPChunkedCount',
                request_serializer=privacy__pb2.DPChunkedCountRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPChunkedSum = channel.unary_unary(
                '/privacy.local.PrivacyService/DPChunkedSum',
                request_serializer=privacy__pb2.DPChunkedSumRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPChunkedMean = channel.unary_unary(
                '/privacy.local.PrivacyService/DPChunkedMean',
                request_serializer=privacy__pb2.DPChunkedMeanRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPResponse.FromString,
                _registered_method=True)
        self.DPChunkedHistogram = channel.unary_unary(
                '/privacy.local.PrivacyService/DPChunkedHistogram',
                request_serializer=privacy__pb2.DPChunkedHistogramRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPHistogramResponse.FromString,
                _registered_method=True)
        self.KAnonymizeRecord = channel.unary_unary(
                '/privacy.local.PrivacyService/KAnonymizeRecord',
                request_serializer=privacy__pb2.KAnonymizeRequest.SerializeToString,
                response_deserializer=privacy__pb2.KAnonymizeResponse.FromString,
                _registered_method=True)
        self.KAnonymizeTable = channel.unary_unary(
                '/privacy.local.PrivacyService/KAnonymizeTable',
                request_serializer=privacy__pb2.KAnonymizeTableRequest.SerializeToString,
                response_deserializer=privacy__pb2.KAnonymizeTableResponse.FromString,
                _registered_method=True)
        self.KAnonymizeDataFrame = channel.unary_unary(
                '/privacy.local.PrivacyService/KAnonymizeDataFrame',
                request_serializer=privacy__pb2.KAnonymizeDataFrameRequest.SerializeToString,
                response_deserializer=privacy__pb2.KAnonymizeDataFrameResponse.FromString,
                _registered_method=True)
        self.ObfuscateQuery = channel.unary_unary(
                '/privacy.local.PrivacyService/ObfuscateQuery',
                request_serializer=privacy__pb2.ObfuscateQueryRequest.SerializeToString,
                response_deserializer=privacy__pb2.ObfuscateQueryResponse.FromString,
                _registered_method=True)
        self.ObfuscateQueryBatch = channel.unary_unary(
                '/privacy.local.PrivacyService/ObfuscateQueryBatch',
                request_serializer=privacy__pb2.ObfuscateQueryBatchRequest.SerializeToString,
                response_deserializer=privacy__pb2.ObfuscateQueryBatchResponse.FromString,
                _registered_method=True)
        self.ClassifyField = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyField',
                request_serializer=privacy__pb2.ClassifyFieldRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyFieldResponse.FromString,
                _registered_method=True)
        self.ClassifyRecord = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyRecord',
                request_serializer=privacy__pb2.ClassifyRecordRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyRecordResponse.FromString,
                _registered_method=True)
        self.ClassifyTable = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyTable',
                request_serializer=privacy__pb2.ClassifyTableRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyTableResponse.FromString,
                _registered_method=True)
        self.ClassifyTableAsync = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifyTableAsync',
                request_serializer=privacy__pb2.ClassifyTableAsyncRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifyTableAsyncResponse.FromString,
                _registered_method=True)
        self.GetClassificationJob = channel.unary_unary(
                '/privacy.local.PrivacyService/GetClassificationJob',
                request_serializer=privacy__pb2.GetClassificationJobRequest.SerializeToString,
                response_deserializer=privacy__pb2.GetClassificationJobResponse.FromString,
                _registered_method=True)
        self.ClassifySecretFlow = channel.unary_unary(
                '/privacy.local.PrivacyService/ClassifySecretFlow',
                request_serializer=privacy__pb2.ClassifySecretFlowRequest.SerializeToString,
                response_deserializer=privacy__pb2.ClassifySecretFlowResponse.FromString,
                _registered_method=True)
        self.ConfirmReview = channel.unary_unary(
                '/privacy.local.PrivacyService/ConfirmReview',
                request_serializer=privacy__pb2.ConfirmReviewRequest.SerializeToString,
                response_deserializer=privacy__pb2.ConfirmReviewResponse.FromString,
                _registered_method=True)
        self.ExportReviews = channel.unary_unary(
                '/privacy.local.PrivacyService/ExportReviews',
                request_serializer=privacy__pb2.ExportReviewsRequest.SerializeToString,
                response_deserializer=privacy__pb2.ExportReviewsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/privacy.local.PrivacyService/Health',
                request_serializer=privacy__pb2.HealthRequest.SerializeToString,
                response_deserializer=privacy__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RecommendParams = channel.unary_unary(
                '/privacy.local.PrivacyService/RecommendParams',
                request_serializer=privacy__pb2.RecommendRequest.SerializeToString,
                response_deserializer=privacy__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.PerturbBinaryBatch = channel.unary_unary(
                '/privacy.local.PrivacyService/PerturbBinaryBatch',
                request_serializer=privacy__pb2.PerturbBinaryBatchRequest.SerializeToString,
                response_deserializer=privacy__pb2.PerturbBinaryBatchResponse.FromString,
                _registered_method=True)
        self.PerturbCategoricalBatch = channel.unary_unary(
                '/privacy.local.PrivacyService/PerturbCategoricalBatch',
                request_serializer=privacy__pb2.PerturbCategoricalBatchRequest.SerializeToString,
                response_deserializer=privacy__pb2.PerturbCategoricalBatchResponse.FromString,
                _registered_method=True)
        self.EstimateBinaryFrequency = channel.unary_unary(
                '/privacy.local.PrivacyService/EstimateBinaryFrequency',
                request_serializer=privacy__pb2.EstimateBinaryFrequencyRequest.SerializeToString,
                response_deserializer=privacy__pb2.EstimateBinaryFrequencyResponse.FromString,
                _registered_method=True)
        self.EstimateCategoricalHistogram = channel.unary_unary(
                '/privacy.local.PrivacyService/EstimateCategoricalHistogram',
                request_serializer=privacy__pb2.EstimateCategoricalHistogramRequest.SerializeToString,
                response_deserializer=privacy__pb2.EstimateCategoricalHistogramResponse.FromString,
                _registered_method=True)
        self.DPAggregate = channel.unary_unary(
                '/privacy.local.PrivacyService/DPAggregate',
                request_serializer=privacy__pb2.DPAggregateRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPAggregateResponse.FromString,
                _registered_method=True)
        self.DPVectorSum = channel.unary_unary(
                '/privacy.local.PrivacyService/DPVectorSum',
                request_serializer=privacy__pb2.DPVectorSumRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPVectorSumResponse.FromString,
                _registered_method=True)
        self.DPAdaptiveClip = channel.unary_unary(
                '/privacy.local.PrivacyService/DPAdaptiveClip',
                request_serializer=privacy__pb2.DPAdaptiveClipRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPAdaptiveClipResponse.FromString,
                _registered_method=True)
        self.DPGroupBy = channel.unary_unary(
                '/privacy.local.PrivacyService/DPGroupBy',
                request_serializer=privacy__pb2.DPGroupByRequest.SerializeToString,
                response_deserializer=privacy__pb2.DPGroupByResponse.FromString,
                _registered_method=True)


class PrivacyServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Mask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaskRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaskBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaskDataFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPMean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPHistogram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPNoisyCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPNoisySum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPNoisyMean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPNoisyHistogram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPChunkedCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPChunkedSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPChunkedMean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPChunkedHistogram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KAnonymizeRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KAnonymizeTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KAnonymizeDataFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObfuscateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObfuscateQueryBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyTableAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClassificationJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifySecretFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerturbBinaryBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerturbCategoricalBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateBinaryFrequency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateCategoricalHistogram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPAggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPVectorSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPAdaptiveClip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DPGroupBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivacyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Mask': grpc.unary_unary_rpc_method_handler(
                    servicer.Mask,
                    request_deserializer=privacy__pb2.MaskRequest.FromString,
                    response_serializer=privacy__pb2.MaskResponse.SerializeToString,
            ),
            'MaskRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.MaskRecord,
                    request_deserializer=privacy__pb2.MaskRecordRequest.FromString,
                    response_serializer=privacy__pb2.MaskRecordResponse.SerializeToString,
            ),
            'MaskBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.MaskBatch,
                    request_deserializer=privacy__pb2.MaskBatchRequest.FromString,
                    response_serializer=privacy__pb2.MaskBatchResponse.SerializeToString,
            ),
            'MaskDataFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.MaskDataFrame,
                    request_deserializer=privacy__pb2.MaskDataFrameRequest.FromString,
                    response_serializer=privacy__pb2.MaskDataFrameResponse.SerializeToString,
            ),
            'Hash': grpc.unary_unary_rpc_method_handler(
                    servicer.Hash,
                    request_deserializer=privacy__pb2.HashRequest.FromString,
                    response_serializer=privacy__pb2.HashResponse.SerializeToString,
            ),
            'DPCount': grpc.unary_unary_rpc_method_handler(
                    servicer.DPCount,
                    request_deserializer=privacy__pb2.DPRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPSum': grpc.unary_unary_rpc_method_handler(
                    servicer.DPSum,
                    request_deserializer=privacy__pb2.DPRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPMean': grpc.unary_unary_rpc_method_handler(
                    servicer.DPMean,
                    request_deserializer=privacy__pb2.DPRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPHistogram': grpc.unary_unary_rpc_method_handler(
                    servicer.DPHistogram,
                    request_deserializer=privacy__pb2.DPHistogramRequest.FromString,
                    response_serializer=privacy__pb2.DPHistogramResponse.SerializeToString,
            ),
            'DPNoisyCount': grpc.unary_unary_rpc_method_handler(
                    servicer.DPNoisyCount,
                    request_deserializer=privacy__pb2.DPNoisyCountRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPNoisySum': grpc.unary_unary_rpc_method_handler(
                    servicer.DPNoisySum,
                    request_deserializer=privacy__pb2.DPNoisySumRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPNoisyMean': grpc.unary_unary_rpc_method_handler(
                    servicer.DPNoisyMean,
                    request_deserializer=privacy__pb2.DPNoisyMeanRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPNoisyHistogram': grpc.unary_unary_rpc_method_handler(
                    servicer.DPNoisyHistogram,
                    request_deserializer=privacy__pb2.DPNoisyHistogramRequest.FromString,
                    response_serializer=privacy__pb2.DPHistogramResponse.SerializeToString,
            ),
            'DPChunkedCount': grpc.unary_unary_rpc_method_handler(
                    servicer.DPChunkedCount,
                    request_deserializer=privacy__pb2.DPChunkedCountRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPChunkedSum': grpc.unary_unary_rpc_method_handler(
                    servicer.DPChunkedSum,
                    request_deserializer=privacy__pb2.DPChunkedSumRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPChunkedMean': grpc.unary_unary_rpc_method_handler(
                    servicer.DPChunkedMean,
                    request_deserializer=privacy__pb2.DPChunkedMeanRequest.FromString,
                    response_serializer=privacy__pb2.DPResponse.SerializeToString,
            ),
            'DPChunkedHistogram': grpc.unary_unary_rpc_method_handler(
                    servicer.DPChunkedHistogram,
                    request_deserializer=privacy__pb2.DPChunkedHistogramRequest.FromString,
                    response_serializer=privacy__pb2.DPHistogramResponse.SerializeToString,
            ),
            'KAnonymizeRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.KAnonymizeRecord,
                    request_deserializer=privacy__pb2.KAnonymizeRequest.FromString,
                    response_serializer=privacy__pb2.KAnonymizeResponse.SerializeToString,
            ),
            'KAnonymizeTable': grpc.unary_unary_rpc_method_handler(
                    servicer.KAnonymizeTable,
                    request_deserializer=privacy__pb2.KAnonymizeTableRequest.FromString,
                    response_serializer=privacy__pb2.KAnonymizeTableResponse.SerializeToString,
            ),
            'KAnonymizeDataFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.KAnonymizeDataFrame,
                    request_deserializer=privacy__pb2.KAnonymizeDataFrameRequest.FromString,
                    response_serializer=privacy__pb2.KAnonymizeDataFrameResponse.SerializeToString,
            ),
            'ObfuscateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ObfuscateQuery,
                    request_deserializer=privacy__pb2.ObfuscateQueryRequest.FromString,
                    response_serializer=privacy__pb2.ObfuscateQueryResponse.SerializeToString,
            ),
            'ObfuscateQueryBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ObfuscateQueryBatch,
                    request_deserializer=privacy__pb2.ObfuscateQueryBatchRequest.FromString,
                    response_serializer=privacy__pb2.ObfuscateQueryBatchResponse.SerializeToString,
            ),
            'ClassifyField': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyField,
                    request_deserializer=privacy__pb2.ClassifyFieldRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyFieldResponse.SerializeToString,
            ),
            'ClassifyRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyRecord,
                    request_deserializer=privacy__pb2.ClassifyRecordRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyRecordResponse.SerializeToString,
            ),
            'ClassifyTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyTable,
                    request_deserializer=privacy__pb2.ClassifyTableRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyTableResponse.SerializeToString,
            ),
            'ClassifyTableAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyTableAsync,
                    request_deserializer=privacy__pb2.ClassifyTableAsyncRequest.FromString,
                    response_serializer=privacy__pb2.ClassifyTableAsyncResponse.SerializeToString,
            ),
            'GetClassificationJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClassificationJob,
                    request_deserializer=privacy__pb2.GetClassificationJobRequest.FromString,
                    response_serializer=privacy__pb2.GetClassificationJobResponse.SerializeToString,
            ),
            'ClassifySecretFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifySecretFlow,
                    request_deserializer=privacy__pb2.ClassifySecretFlowRequest.FromString,
                    response_serializer=privacy__pb2.ClassifySecretFlowResponse.SerializeToString,
            ),
            'ConfirmReview': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmReview,
                    request_deserializer=privacy__pb2.ConfirmReviewRequest.FromString,
                    response_serializer=privacy__pb2.ConfirmReviewResponse.SerializeToString,
            ),
            'ExportReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportReviews,
                    request_deserializer=privacy__pb2.ExportReviewsRequest.FromString,
                    response_serializer=privacy__pb2.ExportReviewsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=privacy__pb2.HealthRequest.FromString,
                    response_serializer=privacy__pb2.HealthResponse.SerializeToString,
            ),
            'RecommendParams': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendParams,
                    request_deserializer=privacy__pb2.RecommendRequest.FromString,
                    response_serializer=privacy__pb2.RecommendResponse.SerializeToString,
            ),
            'PerturbBinaryBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PerturbBinaryBatch,
                    request_deserializer=privacy__pb2.PerturbBinaryBatchRequest.FromString,
                    response_serializer=privacy__pb2.PerturbBinaryBatchResponse.SerializeToString,
            ),
            'PerturbCategoricalBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PerturbCategoricalBatch,
                    request_deserializer=privacy__pb2.PerturbCategoricalBatchRequest.FromString,
                    response_serializer=privacy__pb2.PerturbCategoricalBatchResponse.SerializeToString,
            ),
            'EstimateBinaryFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateBinaryFrequency,
                    request_deserializer=privacy__pb2.EstimateBinaryFrequencyRequest.FromString,
                    response_serializer=privacy__pb2.EstimateBinaryFrequencyResponse.SerializeToString,
            ),
            'EstimateCategoricalHistogram': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateCategoricalHistogram,
                    request_deserializer=privacy__pb2.EstimateCategoricalHistogramRequest.FromString,
                    response_serializer=privacy__pb2.EstimateCategoricalHistogramResponse.SerializeToString,
            ),
            'DPAggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.DPAggregate,
                    request_deserializer=privacy__pb2.DPAggregateRequest.FromString,
                    response_serializer=privacy__pb2.DPAggregateResponse.SerializeToString,
            ),
            'DPVectorSum': grpc.unary_unary_rpc_method_handler(
                    servicer.DPVectorSum,
                    request_deserializer=privacy__pb2.DPVectorSumRequest.FromString,
                    response_serializer=privacy__pb2.DPVectorSumResponse.SerializeToString,
            ),
            'DPAdaptiveClip': grpc.unary_unary_rpc_method_handler(
                    servicer.DPAdaptiveClip,
                    request_deserializer=privacy__pb2.DPAdaptiveClipRequest.FromString,
                    response_serializer=privacy__pb2.DPAdaptiveClipResponse.SerializeToString,
            ),
            'DPGroupBy': grpc.unary_unary_rpc_method_handler(
                    servicer.DPGroupBy,
                    request_deserializer=privacy__pb2.DPGroupByRequest.FromString,
                    response_serializer=privacy__pb2.DPGroupByResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privacy.local.PrivacyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privacy.local.PrivacyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrivacyService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Mask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/Mask',
            privacy__pb2.MaskRequest.SerializeToString,
            privacy__pb2.MaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaskRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/MaskRecord',
            privacy__pb2.MaskRecordRequest.SerializeToString,
            privacy__pb2.MaskRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaskBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/MaskBatch',
            privacy__pb2.MaskBatchRequest.SerializeToString,
            privacy__pb2.MaskBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaskDataFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/MaskDataFrame',
            privacy__pb2.MaskDataFrameRequest.SerializeToString,
            privacy__pb2.MaskDataFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/Hash',
            privacy__pb2.HashRequest.SerializeToString,
            privacy__pb2.HashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPCount',
            privacy__pb2.DPRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPSum',
            privacy__pb2.DPRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPMean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPMean',
            privacy__pb2.DPRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPHistogram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPHistogram',
            privacy__pb2.DPHistogramRequest.SerializeToString,
            privacy__pb2.DPHistogramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPNoisyCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPNoisyCount',
            privacy__pb2.DPNoisyCountRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPNoisySum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPNoisySum',
            privacy__pb2.DPNoisySumRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPNoisyMean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPNoisyMean',
            privacy__pb2.DPNoisyMeanRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPNoisyHistogram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPNoisyHistogram',
            privacy__pb2.DPNoisyHistogramRequest.SerializeToString,
            privacy__pb2.DPHistogramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPChunkedCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPChunkedCount',
            privacy__pb2.DPChunkedCountRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPChunkedSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPChunkedSum',
            privacy__pb2.DPChunkedSumRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPChunkedMean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPChunkedMean',
            privacy__pb2.DPChunkedMeanRequest.SerializeToString,
            privacy__pb2.DPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPChunkedHistogram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPChunkedHistogram',
            privacy__pb2.DPChunkedHistogramRequest.SerializeToString,
            privacy__pb2.DPHistogramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KAnonymizeRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/KAnonymizeRecord',
            privacy__pb2.KAnonymizeRequest.SerializeToString,
            privacy__pb2.KAnonymizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KAnonymizeTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/KAnonymizeTable',
            privacy__pb2.KAnonymizeTableRequest.SerializeToString,
            privacy__pb2.KAnonymizeTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KAnonymizeDataFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/KAnonymizeDataFrame',
            privacy__pb2.KAnonymizeDataFrameRequest.SerializeToString,
            privacy__pb2.KAnonymizeDataFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObfuscateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ObfuscateQuery',
            privacy__pb2.ObfuscateQueryRequest.SerializeToString,
            privacy__pb2.ObfuscateQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObfuscateQueryBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ObfuscateQueryBatch',
            privacy__pb2.ObfuscateQueryBatchRequest.SerializeToString,
            privacy__pb2.ObfuscateQueryBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyField',
            privacy__pb2.ClassifyFieldRequest.SerializeToString,
            privacy__pb2.ClassifyFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyRecord',
            privacy__pb2.ClassifyRecordRequest.SerializeToString,
            privacy__pb2.ClassifyRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyTable',
            privacy__pb2.ClassifyTableRequest.SerializeToString,
            privacy__pb2.ClassifyTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyTableAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifyTableAsync',
            privacy__pb2.ClassifyTableAsyncRequest.SerializeToString,
            privacy__pb2.ClassifyTableAsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClassificationJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/GetClassificationJob',
            privacy__pb2.GetClassificationJobRequest.SerializeToString,
            privacy__pb2.GetClassificationJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifySecretFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ClassifySecretFlow',
            privacy__pb2.ClassifySecretFlowRequest.SerializeToString,
            privacy__pb2.ClassifySecretFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ConfirmReview',
            privacy__pb2.ConfirmReviewRequest.SerializeToString,
            privacy__pb2.ConfirmReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/ExportReviews',
            privacy__pb2.ExportReviewsRequest.SerializeToString,
            privacy__pb2.ExportReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/Health',
            privacy__pb2.HealthRequest.SerializeToString,
            privacy__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/RecommendParams',
            privacy__pb2.RecommendRequest.SerializeToString,
            privacy__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerturbBinaryBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/PerturbBinaryBatch',
            privacy__pb2.PerturbBinaryBatchRequest.SerializeToString,
            privacy__pb2.PerturbBinaryBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerturbCategoricalBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/PerturbCategoricalBatch',
            privacy__pb2.PerturbCategoricalBatchRequest.SerializeToString,
            privacy__pb2.PerturbCategoricalBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateBinaryFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/EstimateBinaryFrequency',
            privacy__pb2.EstimateBinaryFrequencyRequest.SerializeToString,
            privacy__pb2.EstimateBinaryFrequencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateCategoricalHistogram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/EstimateCategoricalHistogram',
            privacy__pb2.EstimateCategoricalHistogramRequest.SerializeToString,
            privacy__pb2.EstimateCategoricalHistogramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPAggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPAggregate',
            privacy__pb2.DPAggregateRequest.SerializeToString,
            privacy__pb2.DPAggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPVectorSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPVectorSum',
            privacy__pb2.DPVectorSumRequest.SerializeToString,
            privacy__pb2.DPVectorSumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPAdaptiveClip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPAdaptiveClip',
            privacy__pb2.DPAdaptiveClipRequest.SerializeToString,
            privacy__pb2.DPAdaptiveClipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DPGroupBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privacy.local.PrivacyService/DPGroupBy',
            privacy__pb2.DPGroupByRequest.SerializeToString,
            privacy__pb2.DPGroupByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
