apiVersion: v1
kind: Service
metadata:
  name: privacy-local-agent
  namespace: privacy-local-agent
  labels:
    app: privacy-local-agent
spec:
  type: ClusterIP
  selector:
    app: privacy-local-agent
  ports:
    - name: http
      port: 8079
      targetPort: 8079
    - name: grpc
      port: 50051
      targetPort: 50051
