// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: privacy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivacyService_Mask_FullMethodName                         = "/privacy.local.PrivacyService/Mask"
	PrivacyService_MaskRecord_FullMethodName                   = "/privacy.local.PrivacyService/MaskRecord"
	PrivacyService_MaskBatch_FullMethodName                    = "/privacy.local.PrivacyService/MaskBatch"
	PrivacyService_MaskDataFrame_FullMethodName                = "/privacy.local.PrivacyService/MaskDataFrame"
	PrivacyService_Hash_FullMethodName                         = "/privacy.local.PrivacyService/Hash"
	PrivacyService_DPCount_FullMethodName                      = "/privacy.local.PrivacyService/DPCount"
	PrivacyService_DPSum_FullMethodName                        = "/privacy.local.PrivacyService/DPSum"
	PrivacyService_DPMean_FullMethodName                       = "/privacy.local.PrivacyService/DPMean"
	PrivacyService_DPHistogram_FullMethodName                  = "/privacy.local.PrivacyService/DPHistogram"
	PrivacyService_DPNoisyCount_FullMethodName                 = "/privacy.local.PrivacyService/DPNoisyCount"
	PrivacyService_DPNoisySum_FullMethodName                   = "/privacy.local.PrivacyService/DPNoisySum"
	PrivacyService_DPNoisyMean_FullMethodName                  = "/privacy.local.PrivacyService/DPNoisyMean"
	PrivacyService_DPNoisyHistogram_FullMethodName             = "/privacy.local.PrivacyService/DPNoisyHistogram"
	PrivacyService_DPChunkedCount_FullMethodName               = "/privacy.local.PrivacyService/DPChunkedCount"
	PrivacyService_DPChunkedSum_FullMethodName                 = "/privacy.local.PrivacyService/DPChunkedSum"
	PrivacyService_DPChunkedMean_FullMethodName                = "/privacy.local.PrivacyService/DPChunkedMean"
	PrivacyService_DPChunkedHistogram_FullMethodName           = "/privacy.local.PrivacyService/DPChunkedHistogram"
	PrivacyService_KAnonymizeRecord_FullMethodName             = "/privacy.local.PrivacyService/KAnonymizeRecord"
	PrivacyService_KAnonymizeTable_FullMethodName              = "/privacy.local.PrivacyService/KAnonymizeTable"
	PrivacyService_KAnonymizeDataFrame_FullMethodName          = "/privacy.local.PrivacyService/KAnonymizeDataFrame"
	PrivacyService_ObfuscateQuery_FullMethodName               = "/privacy.local.PrivacyService/ObfuscateQuery"
	PrivacyService_ObfuscateQueryBatch_FullMethodName          = "/privacy.local.PrivacyService/ObfuscateQueryBatch"
	PrivacyService_ClassifyField_FullMethodName                = "/privacy.local.PrivacyService/ClassifyField"
	PrivacyService_ClassifyRecord_FullMethodName               = "/privacy.local.PrivacyService/ClassifyRecord"
	PrivacyService_ClassifyTable_FullMethodName                = "/privacy.local.PrivacyService/ClassifyTable"
	PrivacyService_ClassifyTableAsync_FullMethodName           = "/privacy.local.PrivacyService/ClassifyTableAsync"
	PrivacyService_GetClassificationJob_FullMethodName         = "/privacy.local.PrivacyService/GetClassificationJob"
	PrivacyService_ClassifySecretFlow_FullMethodName           = "/privacy.local.PrivacyService/ClassifySecretFlow"
	PrivacyService_ConfirmReview_FullMethodName                = "/privacy.local.PrivacyService/ConfirmReview"
	PrivacyService_ExportReviews_FullMethodName                = "/privacy.local.PrivacyService/ExportReviews"
	PrivacyService_Health_FullMethodName                       = "/privacy.local.PrivacyService/Health"
	PrivacyService_RecommendParams_FullMethodName              = "/privacy.local.PrivacyService/RecommendParams"
	PrivacyService_PerturbBinaryBatch_FullMethodName           = "/privacy.local.PrivacyService/PerturbBinaryBatch"
	PrivacyService_PerturbCategoricalBatch_FullMethodName      = "/privacy.local.PrivacyService/PerturbCategoricalBatch"
	PrivacyService_EstimateBinaryFrequency_FullMethodName      = "/privacy.local.PrivacyService/EstimateBinaryFrequency"
	PrivacyService_EstimateCategoricalHistogram_FullMethodName = "/privacy.local.PrivacyService/EstimateCategoricalHistogram"
	PrivacyService_DPAggregate_FullMethodName                  = "/privacy.local.PrivacyService/DPAggregate"
	PrivacyService_DPVectorSum_FullMethodName                  = "/privacy.local.PrivacyService/DPVectorSum"
	PrivacyService_DPAdaptiveClip_FullMethodName               = "/privacy.local.PrivacyService/DPAdaptiveClip"
	PrivacyService_DPGroupBy_FullMethodName                    = "/privacy.local.PrivacyService/DPGroupBy"
)

// PrivacyServiceClient is the client API for PrivacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivacyServiceClient interface {
	Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error)
	MaskRecord(ctx context.Context, in *MaskRecordRequest, opts ...grpc.CallOption) (*MaskRecordResponse, error)
	MaskBatch(ctx context.Context, in *MaskBatchRequest, opts ...grpc.CallOption) (*MaskBatchResponse, error)
	MaskDataFrame(ctx context.Context, in *MaskDataFrameRequest, opts ...grpc.CallOption) (*MaskDataFrameResponse, error)
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	DPCount(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPSum(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPMean(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPHistogram(ctx context.Context, in *DPHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error)
	DPNoisyCount(ctx context.Context, in *DPNoisyCountRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPNoisySum(ctx context.Context, in *DPNoisySumRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPNoisyMean(ctx context.Context, in *DPNoisyMeanRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPNoisyHistogram(ctx context.Context, in *DPNoisyHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error)
	DPChunkedCount(ctx context.Context, in *DPChunkedCountRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPChunkedSum(ctx context.Context, in *DPChunkedSumRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPChunkedMean(ctx context.Context, in *DPChunkedMeanRequest, opts ...grpc.CallOption) (*DPResponse, error)
	DPChunkedHistogram(ctx context.Context, in *DPChunkedHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error)
	KAnonymizeRecord(ctx context.Context, in *KAnonymizeRequest, opts ...grpc.CallOption) (*KAnonymizeResponse, error)
	KAnonymizeTable(ctx context.Context, in *KAnonymizeTableRequest, opts ...grpc.CallOption) (*KAnonymizeTableResponse, error)
	KAnonymizeDataFrame(ctx context.Context, in *KAnonymizeDataFrameRequest, opts ...grpc.CallOption) (*KAnonymizeDataFrameResponse, error)
	ObfuscateQuery(ctx context.Context, in *ObfuscateQueryRequest, opts ...grpc.CallOption) (*ObfuscateQueryResponse, error)
	ObfuscateQueryBatch(ctx context.Context, in *ObfuscateQueryBatchRequest, opts ...grpc.CallOption) (*ObfuscateQueryBatchResponse, error)
	ClassifyField(ctx context.Context, in *ClassifyFieldRequest, opts ...grpc.CallOption) (*ClassifyFieldResponse, error)
	ClassifyRecord(ctx context.Context, in *ClassifyRecordRequest, opts ...grpc.CallOption) (*ClassifyRecordResponse, error)
	ClassifyTable(ctx context.Context, in *ClassifyTableRequest, opts ...grpc.CallOption) (*ClassifyTableResponse, error)
	ClassifyTableAsync(ctx context.Context, in *ClassifyTableAsyncRequest, opts ...grpc.CallOption) (*ClassifyTableAsyncResponse, error)
	GetClassificationJob(ctx context.Context, in *GetClassificationJobRequest, opts ...grpc.CallOption) (*GetClassificationJobResponse, error)
	ClassifySecretFlow(ctx context.Context, in *ClassifySecretFlowRequest, opts ...grpc.CallOption) (*ClassifySecretFlowResponse, error)
	ConfirmReview(ctx context.Context, in *ConfirmReviewRequest, opts ...grpc.CallOption) (*ConfirmReviewResponse, error)
	ExportReviews(ctx context.Context, in *ExportReviewsRequest, opts ...grpc.CallOption) (*ExportReviewsResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	RecommendParams(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
	PerturbBinaryBatch(ctx context.Context, in *PerturbBinaryBatchRequest, opts ...grpc.CallOption) (*PerturbBinaryBatchResponse, error)
	PerturbCategoricalBatch(ctx context.Context, in *PerturbCategoricalBatchRequest, opts ...grpc.CallOption) (*PerturbCategoricalBatchResponse, error)
	EstimateBinaryFrequency(ctx context.Context, in *EstimateBinaryFrequencyRequest, opts ...grpc.CallOption) (*EstimateBinaryFrequencyResponse, error)
	EstimateCategoricalHistogram(ctx context.Context, in *EstimateCategoricalHistogramRequest, opts ...grpc.CallOption) (*EstimateCategoricalHistogramResponse, error)
	DPAggregate(ctx context.Context, in *DPAggregateRequest, opts ...grpc.CallOption) (*DPAggregateResponse, error)
	DPVectorSum(ctx context.Context, in *DPVectorSumRequest, opts ...grpc.CallOption) (*DPVectorSumResponse, error)
	DPAdaptiveClip(ctx context.Context, in *DPAdaptiveClipRequest, opts ...grpc.CallOption) (*DPAdaptiveClipResponse, error)
	DPGroupBy(ctx context.Context, in *DPGroupByRequest, opts ...grpc.CallOption) (*DPGroupByResponse, error)
}

type privacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivacyServiceClient(cc grpc.ClientConnInterface) PrivacyServiceClient {
	return &privacyServiceClient{cc}
}

func (c *privacyServiceClient) Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskResponse)
	err := c.cc.Invoke(ctx, PrivacyService_Mask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) MaskRecord(ctx context.Context, in *MaskRecordRequest, opts ...grpc.CallOption) (*MaskRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskRecordResponse)
	err := c.cc.Invoke(ctx, PrivacyService_MaskRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) MaskBatch(ctx context.Context, in *MaskBatchRequest, opts ...grpc.CallOption) (*MaskBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_MaskBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) MaskDataFrame(ctx context.Context, in *MaskDataFrameRequest, opts ...grpc.CallOption) (*MaskDataFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskDataFrameResponse)
	err := c.cc.Invoke(ctx, PrivacyService_MaskDataFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, PrivacyService_Hash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPCount(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPSum(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPMean(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPHistogram(ctx context.Context, in *DPHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisyCount(ctx context.Context, in *DPNoisyCountRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisyCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisySum(ctx context.Context, in *DPNoisySumRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisySum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisyMean(ctx context.Context, in *DPNoisyMeanRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisyMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPNoisyHistogram(ctx context.Context, in *DPNoisyHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPNoisyHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedCount(ctx context.Context, in *DPChunkedCountRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedSum(ctx context.Context, in *DPChunkedSumRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedMean(ctx context.Context, in *DPChunkedMeanRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPChunkedHistogram(ctx context.Context, in *DPChunkedHistogramRequest, opts ...grpc.CallOption) (*DPHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPChunkedHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) KAnonymizeRecord(ctx context.Context, in *KAnonymizeRequest, opts ...grpc.CallOption) (*KAnonymizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KAnonymizeResponse)
	err := c.cc.Invoke(ctx, PrivacyService_KAnonymizeRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) KAnonymizeTable(ctx context.Context, in *KAnonymizeTableRequest, opts ...grpc.CallOption) (*KAnonymizeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KAnonymizeTableResponse)
	err := c.cc.Invoke(ctx, PrivacyService_KAnonymizeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) KAnonymizeDataFrame(ctx context.Context, in *KAnonymizeDataFrameRequest, opts ...grpc.CallOption) (*KAnonymizeDataFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KAnonymizeDataFrameResponse)
	err := c.cc.Invoke(ctx, PrivacyService_KAnonymizeDataFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ObfuscateQuery(ctx context.Context, in *ObfuscateQueryRequest, opts ...grpc.CallOption) (*ObfuscateQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObfuscateQueryResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ObfuscateQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ObfuscateQueryBatch(ctx context.Context, in *ObfuscateQueryBatchRequest, opts ...grpc.CallOption) (*ObfuscateQueryBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObfuscateQueryBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ObfuscateQueryBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ClassifyField(ctx context.Context, in *ClassifyFieldRequest, opts ...grpc.CallOption) (*ClassifyFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyFieldResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ClassifyField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ClassifyRecord(ctx context.Context, in *ClassifyRecordRequest, opts ...grpc.CallOption) (*ClassifyRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyRecordResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ClassifyRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ClassifyTable(ctx context.Context, in *ClassifyTableRequest, opts ...grpc.CallOption) (*ClassifyTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyTableResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ClassifyTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ClassifyTableAsync(ctx context.Context, in *ClassifyTableAsyncRequest, opts ...grpc.CallOption) (*ClassifyTableAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyTableAsyncResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ClassifyTableAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) GetClassificationJob(ctx context.Context, in *GetClassificationJobRequest, opts ...grpc.CallOption) (*GetClassificationJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClassificationJobResponse)
	err := c.cc.Invoke(ctx, PrivacyService_GetClassificationJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ClassifySecretFlow(ctx context.Context, in *ClassifySecretFlowRequest, opts ...grpc.CallOption) (*ClassifySecretFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifySecretFlowResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ClassifySecretFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ConfirmReview(ctx context.Context, in *ConfirmReviewRequest, opts ...grpc.CallOption) (*ConfirmReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmReviewResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ConfirmReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) ExportReviews(ctx context.Context, in *ExportReviewsRequest, opts ...grpc.CallOption) (*ExportReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReviewsResponse)
	err := c.cc.Invoke(ctx, PrivacyService_ExportReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PrivacyService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) RecommendParams(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, PrivacyService_RecommendParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) PerturbBinaryBatch(ctx context.Context, in *PerturbBinaryBatchRequest, opts ...grpc.CallOption) (*PerturbBinaryBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerturbBinaryBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_PerturbBinaryBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) PerturbCategoricalBatch(ctx context.Context, in *PerturbCategoricalBatchRequest, opts ...grpc.CallOption) (*PerturbCategoricalBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerturbCategoricalBatchResponse)
	err := c.cc.Invoke(ctx, PrivacyService_PerturbCategoricalBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) EstimateBinaryFrequency(ctx context.Context, in *EstimateBinaryFrequencyRequest, opts ...grpc.CallOption) (*EstimateBinaryFrequencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateBinaryFrequencyResponse)
	err := c.cc.Invoke(ctx, PrivacyService_EstimateBinaryFrequency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) EstimateCategoricalHistogram(ctx context.Context, in *EstimateCategoricalHistogramRequest, opts ...grpc.CallOption) (*EstimateCategoricalHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateCategoricalHistogramResponse)
	err := c.cc.Invoke(ctx, PrivacyService_EstimateCategoricalHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPAggregate(ctx context.Context, in *DPAggregateRequest, opts ...grpc.CallOption) (*DPAggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPAggregateResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPAggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPVectorSum(ctx context.Context, in *DPVectorSumRequest, opts ...grpc.CallOption) (*DPVectorSumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPVectorSumResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPVectorSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPAdaptiveClip(ctx context.Context, in *DPAdaptiveClipRequest, opts ...grpc.CallOption) (*DPAdaptiveClipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPAdaptiveClipResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPAdaptiveClip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyServiceClient) DPGroupBy(ctx context.Context, in *DPGroupByRequest, opts ...grpc.CallOption) (*DPGroupByResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPGroupByResponse)
	err := c.cc.Invoke(ctx, PrivacyService_DPGroupBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivacyServiceServer is the server API for PrivacyService service.
// All implementations must embed UnimplementedPrivacyServiceServer
// for forward compatibility.
type PrivacyServiceServer interface {
	Mask(context.Context, *MaskRequest) (*MaskResponse, error)
	MaskRecord(context.Context, *MaskRecordRequest) (*MaskRecordResponse, error)
	MaskBatch(context.Context, *MaskBatchRequest) (*MaskBatchResponse, error)
	MaskDataFrame(context.Context, *MaskDataFrameRequest) (*MaskDataFrameResponse, error)
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	DPCount(context.Context, *DPRequest) (*DPResponse, error)
	DPSum(context.Context, *DPRequest) (*DPResponse, error)
	DPMean(context.Context, *DPRequest) (*DPResponse, error)
	DPHistogram(context.Context, *DPHistogramRequest) (*DPHistogramResponse, error)
	DPNoisyCount(context.Context, *DPNoisyCountRequest) (*DPResponse, error)
	DPNoisySum(context.Context, *DPNoisySumRequest) (*DPResponse, error)
	DPNoisyMean(context.Context, *DPNoisyMeanRequest) (*DPResponse, error)
	DPNoisyHistogram(context.Context, *DPNoisyHistogramRequest) (*DPHistogramResponse, error)
	DPChunkedCount(context.Context, *DPChunkedCountRequest) (*DPResponse, error)
	DPChunkedSum(context.Context, *DPChunkedSumRequest) (*DPResponse, error)
	DPChunkedMean(context.Context, *DPChunkedMeanRequest) (*DPResponse, error)
	DPChunkedHistogram(context.Context, *DPChunkedHistogramRequest) (*DPHistogramResponse, error)
	KAnonymizeRecord(context.Context, *KAnonymizeRequest) (*KAnonymizeResponse, error)
	KAnonymizeTable(context.Context, *KAnonymizeTableRequest) (*KAnonymizeTableResponse, error)
	KAnonymizeDataFrame(context.Context, *KAnonymizeDataFrameRequest) (*KAnonymizeDataFrameResponse, error)
	ObfuscateQuery(context.Context, *ObfuscateQueryRequest) (*ObfuscateQueryResponse, error)
	ObfuscateQueryBatch(context.Context, *ObfuscateQueryBatchRequest) (*ObfuscateQueryBatchResponse, error)
	ClassifyField(context.Context, *ClassifyFieldRequest) (*ClassifyFieldResponse, error)
	ClassifyRecord(context.Context, *ClassifyRecordRequest) (*ClassifyRecordResponse, error)
	ClassifyTable(context.Context, *ClassifyTableRequest) (*ClassifyTableResponse, error)
	ClassifyTableAsync(context.Context, *ClassifyTableAsyncRequest) (*ClassifyTableAsyncResponse, error)
	GetClassificationJob(context.Context, *GetClassificationJobRequest) (*GetClassificationJobResponse, error)
	ClassifySecretFlow(context.Context, *ClassifySecretFlowRequest) (*ClassifySecretFlowResponse, error)
	ConfirmReview(context.Context, *ConfirmReviewRequest) (*ConfirmReviewResponse, error)
	ExportReviews(context.Context, *ExportReviewsRequest) (*ExportReviewsResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	RecommendParams(context.Context, *RecommendRequest) (*RecommendResponse, error)
	PerturbBinaryBatch(context.Context, *PerturbBinaryBatchRequest) (*PerturbBinaryBatchResponse, error)
	PerturbCategoricalBatch(context.Context, *PerturbCategoricalBatchRequest) (*PerturbCategoricalBatchResponse, error)
	EstimateBinaryFrequency(context.Context, *EstimateBinaryFrequencyRequest) (*EstimateBinaryFrequencyResponse, error)
	EstimateCategoricalHistogram(context.Context, *EstimateCategoricalHistogramRequest) (*EstimateCategoricalHistogramResponse, error)
	DPAggregate(context.Context, *DPAggregateRequest) (*DPAggregateResponse, error)
	DPVectorSum(context.Context, *DPVectorSumRequest) (*DPVectorSumResponse, error)
	DPAdaptiveClip(context.Context, *DPAdaptiveClipRequest) (*DPAdaptiveClipResponse, error)
	DPGroupBy(context.Context, *DPGroupByRequest) (*DPGroupByResponse, error)
	mustEmbedUnimplementedPrivacyServiceServer()
}

// UnimplementedPrivacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivacyServiceServer struct{}

func (UnimplementedPrivacyServiceServer) Mask(context.Context, *MaskRequest) (*MaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mask not implemented")
}
func (UnimplementedPrivacyServiceServer) MaskRecord(context.Context, *MaskRecordRequest) (*MaskRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaskRecord not implemented")
}
func (UnimplementedPrivacyServiceServer) MaskBatch(context.Context, *MaskBatchRequest) (*MaskBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaskBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) MaskDataFrame(context.Context, *MaskDataFrameRequest) (*MaskDataFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaskDataFrame not implemented")
}
func (UnimplementedPrivacyServiceServer) Hash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (UnimplementedPrivacyServiceServer) DPCount(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPCount not implemented")
}
func (UnimplementedPrivacyServiceServer) DPSum(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPSum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPMean(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DPHistogram(context.Context, *DPHistogramRequest) (*DPHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisyCount(context.Context, *DPNoisyCountRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisyCount not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisySum(context.Context, *DPNoisySumRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisySum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisyMean(context.Context, *DPNoisyMeanRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisyMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DPNoisyHistogram(context.Context, *DPNoisyHistogramRequest) (*DPHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPNoisyHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedCount(context.Context, *DPChunkedCountRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedCount not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedSum(context.Context, *DPChunkedSumRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedSum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedMean(context.Context, *DPChunkedMeanRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedMean not implemented")
}
func (UnimplementedPrivacyServiceServer) DPChunkedHistogram(context.Context, *DPChunkedHistogramRequest) (*DPHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPChunkedHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) KAnonymizeRecord(context.Context, *KAnonymizeRequest) (*KAnonymizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KAnonymizeRecord not implemented")
}
func (UnimplementedPrivacyServiceServer) KAnonymizeTable(context.Context, *KAnonymizeTableRequest) (*KAnonymizeTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KAnonymizeTable not implemented")
}
func (UnimplementedPrivacyServiceServer) KAnonymizeDataFrame(context.Context, *KAnonymizeDataFrameRequest) (*KAnonymizeDataFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KAnonymizeDataFrame not implemented")
}
func (UnimplementedPrivacyServiceServer) ObfuscateQuery(context.Context, *ObfuscateQueryRequest) (*ObfuscateQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObfuscateQuery not implemented")
}
func (UnimplementedPrivacyServiceServer) ObfuscateQueryBatch(context.Context, *ObfuscateQueryBatchRequest) (*ObfuscateQueryBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObfuscateQueryBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) ClassifyField(context.Context, *ClassifyFieldRequest) (*ClassifyFieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyField not implemented")
}
func (UnimplementedPrivacyServiceServer) ClassifyRecord(context.Context, *ClassifyRecordRequest) (*ClassifyRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyRecord not implemented")
}
func (UnimplementedPrivacyServiceServer) ClassifyTable(context.Context, *ClassifyTableRequest) (*ClassifyTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyTable not implemented")
}
func (UnimplementedPrivacyServiceServer) ClassifyTableAsync(context.Context, *ClassifyTableAsyncRequest) (*ClassifyTableAsyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyTableAsync not implemented")
}
func (UnimplementedPrivacyServiceServer) GetClassificationJob(context.Context, *GetClassificationJobRequest) (*GetClassificationJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassificationJob not implemented")
}
func (UnimplementedPrivacyServiceServer) ClassifySecretFlow(context.Context, *ClassifySecretFlowRequest) (*ClassifySecretFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifySecretFlow not implemented")
}
func (UnimplementedPrivacyServiceServer) ConfirmReview(context.Context, *ConfirmReviewRequest) (*ConfirmReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmReview not implemented")
}
func (UnimplementedPrivacyServiceServer) ExportReviews(context.Context, *ExportReviewsRequest) (*ExportReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportReviews not implemented")
}
func (UnimplementedPrivacyServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPrivacyServiceServer) RecommendParams(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendParams not implemented")
}
func (UnimplementedPrivacyServiceServer) PerturbBinaryBatch(context.Context, *PerturbBinaryBatchRequest) (*PerturbBinaryBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerturbBinaryBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) PerturbCategoricalBatch(context.Context, *PerturbCategoricalBatchRequest) (*PerturbCategoricalBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerturbCategoricalBatch not implemented")
}
func (UnimplementedPrivacyServiceServer) EstimateBinaryFrequency(context.Context, *EstimateBinaryFrequencyRequest) (*EstimateBinaryFrequencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateBinaryFrequency not implemented")
}
func (UnimplementedPrivacyServiceServer) EstimateCategoricalHistogram(context.Context, *EstimateCategoricalHistogramRequest) (*EstimateCategoricalHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateCategoricalHistogram not implemented")
}
func (UnimplementedPrivacyServiceServer) DPAggregate(context.Context, *DPAggregateRequest) (*DPAggregateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPAggregate not implemented")
}
func (UnimplementedPrivacyServiceServer) DPVectorSum(context.Context, *DPVectorSumRequest) (*DPVectorSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPVectorSum not implemented")
}
func (UnimplementedPrivacyServiceServer) DPAdaptiveClip(context.Context, *DPAdaptiveClipRequest) (*DPAdaptiveClipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPAdaptiveClip not implemented")
}
func (UnimplementedPrivacyServiceServer) DPGroupBy(context.Context, *DPGroupByRequest) (*DPGroupByResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPGroupBy not implemented")
}
func (UnimplementedPrivacyServiceServer) mustEmbedUnimplementedPrivacyServiceServer() {}
func (UnimplementedPrivacyServiceServer) testEmbeddedByValue()                        {}

// UnsafePrivacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivacyServiceServer will
// result in compilation errors.
type UnsafePrivacyServiceServer interface {
	mustEmbedUnimplementedPrivacyServiceServer()
}

func RegisterPrivacyServiceServer(s grpc.ServiceRegistrar, srv PrivacyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrivacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivacyService_ServiceDesc, srv)
}

func _PrivacyService_Mask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).Mask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_Mask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).Mask(ctx, req.(*MaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_MaskRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).MaskRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_MaskRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).MaskRecord(ctx, req.(*MaskRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_MaskBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).MaskBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_MaskBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).MaskBatch(ctx, req.(*MaskBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_MaskDataFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskDataFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).MaskDataFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_MaskDataFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).MaskDataFrame(ctx, req.(*MaskDataFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_Hash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPCount(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPSum(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPMean(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPHistogram(ctx, req.(*DPHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisyCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisyCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisyCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisyCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisyCount(ctx, req.(*DPNoisyCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisySum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisySumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisySum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisySum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisySum(ctx, req.(*DPNoisySumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisyMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisyMeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisyMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisyMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisyMean(ctx, req.(*DPNoisyMeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPNoisyHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPNoisyHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPNoisyHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPNoisyHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPNoisyHistogram(ctx, req.(*DPNoisyHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedCount(ctx, req.(*DPChunkedCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedSum(ctx, req.(*DPChunkedSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedMeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedMean(ctx, req.(*DPChunkedMeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPChunkedHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPChunkedHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPChunkedHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPChunkedHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPChunkedHistogram(ctx, req.(*DPChunkedHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_KAnonymizeRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KAnonymizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).KAnonymizeRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_KAnonymizeRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).KAnonymizeRecord(ctx, req.(*KAnonymizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_KAnonymizeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KAnonymizeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).KAnonymizeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_KAnonymizeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).KAnonymizeTable(ctx, req.(*KAnonymizeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_KAnonymizeDataFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KAnonymizeDataFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).KAnonymizeDataFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_KAnonymizeDataFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).KAnonymizeDataFrame(ctx, req.(*KAnonymizeDataFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ObfuscateQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObfuscateQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ObfuscateQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ObfuscateQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ObfuscateQuery(ctx, req.(*ObfuscateQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ObfuscateQueryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObfuscateQueryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ObfuscateQueryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ObfuscateQueryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ObfuscateQueryBatch(ctx, req.(*ObfuscateQueryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ClassifyField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ClassifyField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ClassifyField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ClassifyField(ctx, req.(*ClassifyFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ClassifyRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ClassifyRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ClassifyRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ClassifyRecord(ctx, req.(*ClassifyRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ClassifyTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ClassifyTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ClassifyTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ClassifyTable(ctx, req.(*ClassifyTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ClassifyTableAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyTableAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ClassifyTableAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ClassifyTableAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ClassifyTableAsync(ctx, req.(*ClassifyTableAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_GetClassificationJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassificationJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).GetClassificationJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_GetClassificationJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).GetClassificationJob(ctx, req.(*GetClassificationJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ClassifySecretFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifySecretFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ClassifySecretFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ClassifySecretFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ClassifySecretFlow(ctx, req.(*ClassifySecretFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ConfirmReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ConfirmReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ConfirmReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ConfirmReview(ctx, req.(*ConfirmReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_ExportReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).ExportReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_ExportReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).ExportReviews(ctx, req.(*ExportReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_RecommendParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).RecommendParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_RecommendParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).RecommendParams(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_PerturbBinaryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerturbBinaryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).PerturbBinaryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_PerturbBinaryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).PerturbBinaryBatch(ctx, req.(*PerturbBinaryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_PerturbCategoricalBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerturbCategoricalBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).PerturbCategoricalBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_PerturbCategoricalBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).PerturbCategoricalBatch(ctx, req.(*PerturbCategoricalBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_EstimateBinaryFrequency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateBinaryFrequencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).EstimateBinaryFrequency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_EstimateBinaryFrequency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).EstimateBinaryFrequency(ctx, req.(*EstimateBinaryFrequencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_EstimateCategoricalHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateCategoricalHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).EstimateCategoricalHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_EstimateCategoricalHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).EstimateCategoricalHistogram(ctx, req.(*EstimateCategoricalHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPAggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPAggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPAggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPAggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPAggregate(ctx, req.(*DPAggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPVectorSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPVectorSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPVectorSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPVectorSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPVectorSum(ctx, req.(*DPVectorSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPAdaptiveClip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPAdaptiveClipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPAdaptiveClip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPAdaptiveClip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPAdaptiveClip(ctx, req.(*DPAdaptiveClipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyService_DPGroupBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPGroupByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).DPGroupBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_DPGroupBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).DPGroupBy(ctx, req.(*DPGroupByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivacyService_ServiceDesc is the grpc.ServiceDesc for PrivacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privacy.local.PrivacyService",
	HandlerType: (*PrivacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mask",
			Handler:    _PrivacyService_Mask_Handler,
		},
		{
			MethodName: "MaskRecord",
			Handler:    _PrivacyService_MaskRecord_Handler,
		},
		{
			MethodName: "MaskBatch",
			Handler:    _PrivacyService_MaskBatch_Handler,
		},
		{
			MethodName: "MaskDataFrame",
			Handler:    _PrivacyService_MaskDataFrame_Handler,
		},
		{
			MethodName: "Hash",
			Handler:    _PrivacyService_Hash_Handler,
		},
		{
			MethodName: "DPCount",
			Handler:    _PrivacyService_DPCount_Handler,
		},
		{
			MethodName: "DPSum",
			Handler:    _PrivacyService_DPSum_Handler,
		},
		{
			MethodName: "DPMean",
			Handler:    _PrivacyService_DPMean_Handler,
		},
		{
			MethodName: "DPHistogram",
			Handler:    _PrivacyService_DPHistogram_Handler,
		},
		{
			MethodName: "DPNoisyCount",
			Handler:    _PrivacyService_DPNoisyCount_Handler,
		},
		{
			MethodName: "DPNoisySum",
			Handler:    _PrivacyService_DPNoisySum_Handler,
		},
		{
			MethodName: "DPNoisyMean",
			Handler:    _PrivacyService_DPNoisyMean_Handler,
		},
		{
			MethodName: "DPNoisyHistogram",
			Handler:    _PrivacyService_DPNoisyHistogram_Handler,
		},
		{
			MethodName: "DPChunkedCount",
			Handler:    _PrivacyService_DPChunkedCount_Handler,
		},
		{
			MethodName: "DPChunkedSum",
			Handler:    _PrivacyService_DPChunkedSum_Handler,
		},
		{
			MethodName: "DPChunkedMean",
			Handler:    _PrivacyService_DPChunkedMean_Handler,
		},
		{
			MethodName: "DPChunkedHistogram",
			Handler:    _PrivacyService_DPChunkedHistogram_Handler,
		},
		{
			MethodName: "KAnonymizeRecord",
			Handler:    _PrivacyService_KAnonymizeRecord_Handler,
		},
		{
			MethodName: "KAnonymizeTable",
			Handler:    _PrivacyService_KAnonymizeTable_Handler,
		},
		{
			MethodName: "KAnonymizeDataFrame",
			Handler:    _PrivacyService_KAnonymizeDataFrame_Handler,
		},
		{
			MethodName: "ObfuscateQuery",
			Handler:    _PrivacyService_ObfuscateQuery_Handler,
		},
		{
			MethodName: "ObfuscateQueryBatch",
			Handler:    _PrivacyService_ObfuscateQueryBatch_Handler,
		},
		{
			MethodName: "ClassifyField",
			Handler:    _PrivacyService_ClassifyField_Handler,
		},
		{
			MethodName: "ClassifyRecord",
			Handler:    _PrivacyService_ClassifyRecord_Handler,
		},
		{
			MethodName: "ClassifyTable",
			Handler:    _PrivacyService_ClassifyTable_Handler,
		},
		{
			MethodName: "ClassifyTableAsync",
			Handler:    _PrivacyService_ClassifyTableAsync_Handler,
		},
		{
			MethodName: "GetClassificationJob",
			Handler:    _PrivacyService_GetClassificationJob_Handler,
		},
		{
			MethodName: "ClassifySecretFlow",
			Handler:    _PrivacyService_ClassifySecretFlow_Handler,
		},
		{
			MethodName: "ConfirmReview",
			Handler:    _PrivacyService_ConfirmReview_Handler,
		},
		{
			MethodName: "ExportReviews",
			Handler:    _PrivacyService_ExportReviews_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PrivacyService_Health_Handler,
		},
		{
			MethodName: "RecommendParams",
			Handler:    _PrivacyService_RecommendParams_Handler,
		},
		{
			MethodName: "PerturbBinaryBatch",
			Handler:    _PrivacyService_PerturbBinaryBatch_Handler,
		},
		{
			MethodName: "PerturbCategoricalBatch",
			Handler:    _PrivacyService_PerturbCategoricalBatch_Handler,
		},
		{
			MethodName: "EstimateBinaryFrequency",
			Handler:    _PrivacyService_EstimateBinaryFrequency_Handler,
		},
		{
			MethodName: "EstimateCategoricalHistogram",
			Handler:    _PrivacyService_EstimateCategoricalHistogram_Handler,
		},
		{
			MethodName: "DPAggregate",
			Handler:    _PrivacyService_DPAggregate_Handler,
		},
		{
			MethodName: "DPVectorSum",
			Handler:    _PrivacyService_DPVectorSum_Handler,
		},
		{
			MethodName: "DPAdaptiveClip",
			Handler:    _PrivacyService_DPAdaptiveClip_Handler,
		},
		{
			MethodName: "DPGroupBy",
			Handler:    _PrivacyService_DPGroupBy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privacy.proto",
}
