apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "privacy-local-agent.fullname" . }}-config
  labels:
    {{- include "privacy-local-agent.labels" . | nindent 4 }}
data:
  privacy-profile.yaml: |
    {{- .Values.agent.profile | nindent 4 }}
