{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "privacy-local-agent.fullname" . }}
  labels:
    {{- include "privacy-local-agent.labels" . | nindent 4 }}
{{- end }}
