{{- if or (and .Values.security.tls.enabled (not .Values.security.tls.existingSecret) .Values.security.tls.cert) (and .Values.security.auth.enabled (not .Values.security.auth.apiKeysSecret) .Values.security.auth.apiKeys) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacy-local-agent.fullname" . }}-secrets
  labels:
    {{- include "privacy-local-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.security.tls.enabled (not .Values.security.tls.existingSecret) .Values.security.tls.cert }}
  tls.crt: |
    {{- .Values.security.tls.cert | nindent 4 }}
  tls.key: |
    {{- .Values.security.tls.key | nindent 4 }}
  {{- end }}
  {{- if and .Values.security.auth.enabled (not .Values.security.auth.apiKeysSecret) .Values.security.auth.apiKeys }}
  api_keys: |
    {{- .Values.security.auth.apiKeys | nindent 4 }}
  {{- end }}
{{- end }}
